var annotated_dup =
[
    [ "Billboard", "class_billboard.html", null ],
    [ "ButtonUI", "class_button_u_i.html", "class_button_u_i" ],
    [ "CameraController", "class_camera_controller.html", null ],
    [ "CameraRotate", "class_camera_rotate.html", null ],
    [ "DisableCameraOnUIHover", "class_disable_camera_on_u_i_hover.html", null ],
    [ "GameData", "class_game_data.html", null ],
    [ "HeightMaterial", "class_height_material.html", "class_height_material" ],
    [ "IDisplayData", "interface_i_display_data.html", null ],
    [ "MaterialEffect", "class_material_effect.html", "class_material_effect" ],
    [ "Paint", "class_paint.html", "class_paint" ],
    [ "PlayerCurrency", "class_player_currency.html", null ],
    [ "PointAndClick", "class_point_and_click.html", "class_point_and_click" ],
    [ "Prop", "class_prop.html", "class_prop" ],
    [ "PropCategory", "class_prop_category.html", "class_prop_category" ],
    [ "PropData", "class_prop_data.html", null ],
    [ "PropGrid", "class_prop_grid.html", "class_prop_grid" ],
    [ "PropGridData", "class_prop_grid_data.html", null ],
    [ "PropGridSave", "class_prop_grid_save.html", "class_prop_grid_save" ],
    [ "PropPaint", "class_prop_paint.html", "class_prop_paint" ],
    [ "PropTilemap", "class_prop_tilemap.html", "class_prop_tilemap" ],
    [ "PropTilemapCardinal", "class_prop_tilemap_cardinal.html", "class_prop_tilemap_cardinal" ],
    [ "PropTilemapCorners3d", "class_prop_tilemap_corners3d.html", "class_prop_tilemap_corners3d" ],
    [ "SelectionShadow", "class_selection_shadow.html", "class_selection_shadow" ],
    [ "UILoadButtons", "class_u_i_load_buttons.html", "class_u_i_load_buttons" ],
    [ "UIPaint", "class_u_i_paint.html", "class_u_i_paint" ],
    [ "UIProp", "class_u_i_prop.html", "class_u_i_prop" ],
    [ "UIPropGridSave", "class_u_i_prop_grid_save.html", null ]
];